### PR TITLE
c53-fix-pool-overflow-error

### PR DESCRIPTION
**Pull request by TheOneHoff**
## Change Summary
Fixed an issue where db connections were not being returned to the pool after use

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [x] The pull request title has an issue number
- [x] The code works by "Smoke testing" (in other words, you have tested it your own and it works)
- [ ] The code has documentation (either comments or in main documentation platform)

## Other Information
**[Is there anything in particular in the review that I should be aware of?]**

### CODE REVIEW

**Comment by frinzekt** [comment]
Is there supposed to be an indentation in the lines of code?

Also can you please edit your PR title to have the issue number? 🙂

**Comment by TheOneHoff** [comment]
Title renamed and issue is linked

**Comment by TheOneHoff** [comment]
The indentation is correct. session.close() is called within the correct scope in order to close the connection as soon as possible

**Comment by TheOneHoff** [comment]
Nvm. Does not work currently

**Pull request closed without merging**
